import './globals.css';
import { ReactNode } from 'react';
import { Providers } from '../store/provider';

export const metadata = {
  title: 'Your App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
