name: Deploy to GoDaddy via FTP

on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Deploy to GoDaddy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./out/
          server-dir: /public_html/
          dry-run: false
          passive: true
          log-level: verbose
          exclude: |
            **/.git*
            **/node_modules/**
            **/.next/**
